services:
  food-chatbot:
    build:
      context: .
      target: runtime
    command: python -m food_chatbot
    ports:
      - "7860:7860"
    env_file:
      - .env
    image: food-chatbot
    container_name: food-chatbot
